### PR TITLE
Add `ensure_applied` to `firewall_rule` to run at compile time

### PR DESCRIPTION
**Pull request by glenjamin**
This allows the user to avoid the problem of a partially failing chef run causing a bunch of firewall rules to be dropped as discussed in #106

The implementation is based on that of `chef_gem` in core.

If you're happy with this I think it'd also be good to consider making it the default and bumping the major version number?

### CODE REVIEW

**Comment by martinb3** [comment]
Hi there -- I think I would rather make this the default behavior for all rules, rather than add it as an optional thing. I think the benefit of having the entire set of rules at the outset outweighs the benefit of controlling them at converge time. I'm also thinking of not requiring the action on the firewall rules at all (basically they'd be a no-op), and just having the firewall provider compute all the rules on the fly.

What do you think about that approach? Do you mind if I hold off on this a bit longer until I can try to refactor it further and make it the default to build at compile time? I promise it won't be weeks, just days :+1:

**Comment by glenjamin** [comment]
No huge rush from my point-of-view

Are you thinking that the firewall provider would just do a call to `resources` to grab all the rule resources and compute the change to make from that? Similar to how the zap cookbook figures out what to delete?

That seems like it would work well, I might take a look into it.

**Comment by martinb3** [comment]
@glenjamin I pushed up an example here: https://github.com/chef-cookbooks/firewall/tree/oneshot_rules

It essentially makes the firewall_rule actions no-ops. We'd probably need a way for someone to notify the firewall resource still, in case they programmatically create a rule during convergence of another resource, but we could definitely cover any resources that existed at the end of compile time.

**Comment by glenjamin** [comment]
That looks like a great approach, with this scheme you don't event really need to notify `:restart`, you can just apply `[:install, :restart]` at the beginning - could even call the action something like `:apply` instead.

**Comment by martinb3** [comment]
> could even call the action something like :apply instead

That's exactly what I was thinking too :+1:

**Comment by glenjamin** [comment]
Where shall we go with this next, do you want me to pick up your changes and flesh things out, or do you have time to do that yourself?

**Comment by martinb3** [comment]
@glenjamin I've got a few more of them done already and not pushed up yet. Would you be up for testing once I'm done? 

This is going to be a breaking change either way, so I'd love your thoughts on this question:

If someone creates a firewall_rule during convergence of another custom resource, should they simply do a delayed notify on the firewall with `:apply` as the action? Maybe the `install` action on `firewall` or the default action on `firewall_rule` should also automatically create a delayed notification on `firewall` with `:apply`, so that the rules are always applied at the end? Which one would be better?

**Comment by martinb3** [comment]
Also -- one other concern. What about `action :nothing` on a rule? I guess we can look for that, but if someone does an immediate notify later, to apply it, we wouldn't catch it.

**Comment by martinb3** [comment]
Worse, it's almost impossible for us to evaluate `only_if`/`not_if` on a firewall_rule resource using this solution.

**Comment by glenjamin** [comment]
> If someone creates a firewall_rule during convergence of another custom resource, should they simply do a delayed notify on the firewall with :apply as the action? Maybe the install action on firewall or the default action on firewall_rule should also automatically create a delayed notification on firewall with :apply, so that the rules are always applied at the end? Which one would be better?

I think `:action` shouldn't be automatic, it's up to the user whether to apply at the beginning or the end

> Also -- one other concern. What about action :nothing on a rule? I guess we can look for that, but if someone does an immediate notify later, to apply it, we wouldn't catch it.
> Worse, it's almost impossible for us to evaluate only_if/not_if on a firewall_rule resource using this solution.

I'd be tempted to initially document `action :nothing` and `not_if` / `only_if` as not working, with the workaround being to use a real conditional for now - and see who complains.

**Comment by martinb3** [comment]
>> If someone creates a firewall_rule during convergence of another custom resource, should they simply do a delayed notify on the firewall with :apply as the action? Maybe the install action on firewall or the default action on firewall_rule should also automatically create a delayed notification on firewall with :apply, so that the rules are always applied at the end? Which one would be better?

> I think :action shouldn't be automatic, it's up to the user whether to apply at the beginning or the end

That seems reasonable. I like that folks have the option -- it yields much more idiomatic chef recipe code.

> I'd be tempted to initially document action :nothing and not_if / only_if as not working, with the workaround being to use a real conditional for now - and see who complains.

This has the potential to make the upgrade really painful (not only does the cookbook itself have some of these, but I'd be shooting myself in the foot with a ton of internal cookbooks I've got). There's even some cases where a conditional evaluated at compile time will not be possible if the original conditional was something that required lazy/delayed evaluation.

I wonder if we could defer the rule and add the delayed notification _if_ there's a conditional. This feels like we're asking folks to write very un-idiomatic chef if we break these built-ins that normally work in every chef resource.

**Comment by martinb3** [comment]
At a minimum, I'd want to warn or fail the converge if we saw an only_if / not_if. Maybe that would at least make the transition more manageable.

**Comment by glenjamin** [comment]
Hrm, I suppose it should be fairly easy to evaluate the `only_if` / `not_if` blocks when loading in the resource list?

From a quick look, we can call this resource method: https://github.com/chef/chef/blob/d70014cbcbb99558437587cf03f7b1ec3939df81/lib/chef/resource.rb#L1436

**Comment by glenjamin** [comment]
If this is getting too wacky, the opt-out-able compile time application is still a viable option in my opinion

**Comment by martinb3** [comment]
Thinking about this more, instead of adding a special flag, users could just call `run_action` on every firewall_rule. Or, somewhere towards the end of compile time, they could do:
```
firewall_rules = run_context.resource_collection.select { |item| item.is_a?(Chef::Resource::FirewallRule) }
firewall_rules.each { |firewall_rule|  firewall_rule.run_action(:create) }
```

I'll look more into what Chef is doing with not_if / only_if as maybe we could replicate them. I agree that it's getting a bit wacky though. I'd love to just handle the failed chef run by not running the delayed notification. Maybe there's a way to detect that too.

**Comment by glenjamin** [comment]
> Thinking about this more, instead of adding a special flag, users could just call run_action on every firewall_rule.

IMO the attribute for compile time is preferable to this, as it more clearly indicates intent - and doesn't rely as much on the user having a strong understanding of chef internals. The fact it works by running stuff at compile time is an implementation detail - the key thing is that it will always be applied.

If we go down the `run_action` route I'd suggest renaming the `:create` action on rules to `:enqueue` or similar.


Maybe the best solution is a combination of the oneshot branch and the run_action stuff you just suggested.

https://github.com/chef-cookbooks/firewall/commit/2d58b9a566670bedfe77ec4b0a1effc1df63f45b#diff-d8c10f1046eb27545c2f2fb3eb4b40faR70

Instead of
```ruby
      firewall_rules = run_context.resource_collection.select { |item| item.is_a?(Chef::Resource::FirewallRule) }
      firewall_rules.each do |firewall_rule|
```

How about
```ruby
      firewall_rule_resources = run_context.resource_collection.select { |item| item.is_a?(Chef::Resource::FirewallRule) }
      firewall_rule_resources.each { |r| r.action.each { |a| r.run_action(a) } }
```
And then read the rules attribute as before.

The problem I can think of here is if any `only_if` or `not_if` block expects the recipe to have been converged at the point it's evaluated.

**Comment by martinb3** [comment]
@glenjamin Would you check out the oneshot_rules branch? I think I have found a good workaround for the issue with `not_if`/`only_if` and `action :nothing` -- if that meets your needs, I'll merge it into master. Note that it is currently backwards compatible -- you'll have to explicitly disable the notification firing to firewall on every firewall_rule (there's a new attribute for it, defaults to true). Eventually I'd move the default to false, on a major bump of the version. Thanks for your patience on this! :)

**Comment by glenjamin** [comment]
Looks sensible from the diff.

I'd suggest pulling the resource collection filter code into a helper, and renaming the `restart` action - perhaps go very explicit with `apply_rules`

We're currently running https://github.com/glenjamin/firewall/tree/v2.2.0+compile-by-default in our setup at work and it's not caused problems yet :)

**Comment by martinb3** [comment]
@glenjamin I had considered that refactoring step as well, but I didn't want to rename the action until a major version bump.

**Comment by martinb3** [comment]
Hi @glenjamin -- I've merged the one-shot branch which should make it so you never see partial rulesets applied now, and doesn't require compile time to do it. Let me know if that works for you! Thanks!

**Pull request closed without merging**
