### PR TITLE
Added persistent option defaulted to true to allow --permament auto a…

### PR DESCRIPTION
**Pull request by jasonmcintosh**
…dded on all rules created

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @jasonmcintosh

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by martinb3** [comment]
Hi @jasonmcintosh -- thank you for submitting this. Do you think this is a breaking change? Should we default to false, bump minor version now, and then change to true next time we do a major version bump?

Just trying to figure out how to deal with the version bump.

**Comment by jasonmcintosh** [comment]
Behavior wise it in theory should be a fix vs a break but it's definitely a functionality change on firewalld based systems.  I'll update with a minor bump, default to false, 2.2 bump and set to true.

Note I've not looked at the iptables rhel 7 based config to see if it has the same issue.  If it saves and firewalld doesn't then to keep behavior the same I'd say default to true.

**Comment by agperson** [comment]
All the providers (including RHEL 7 iptables) persist by default with the exception of firewalld, which has an additional "save" action.  I would agree that consistency is preferable, which would argue for removing the one-off "save" action and adopting this approach instead.  Keeping "save" in *as well as* adding this will probably lead to confusion.

Persisting by default is, by the _strict_ SemVer definition, a breaking API change that would require a major version bump.  But since the README states that the API is in flux and firewalld support in particular is incomplete, perhaps a minor bump is appropriate instead.

**Comment by martinb3** [comment]
Thanks for the feedback folks. I'm going to go with a minor bump, given that we did say it's in flux and it's technically backwards compatible (i.e. chef and firewalld won't break), but we won't remove the save action until a major bump. :+1:

**Comment by martinb3** [comment]
@jasonmcintosh Correct me if I'm wrong here -- but shouldn't we just add `--persistent` to the spot where we build rule? As it stands, this will now add a persistent and non-persistent rule (two rules) every time. My understanding is that we don't need two if we just use `--persistent`, right?

**Comment by martinb3** [comment]
Ah, I take it back. I tried it with just `--permanent` and it clearly didn't take effect immediately. So we need both.

**Pull request merged**
