### PR TITLE
Set status_command for iptables-persistent to "true".

### PR DESCRIPTION
**Pull request by williamsjj**
### Description

Set status_command for iptables-persistent to "true".

    * iptables-persistent isn't a real service, so Chef
      can never find it in the process table and runs
      start on it every chef run, unnecessarily reloading
      the firewall rules when there is no change in the
      rule set.
    * Setting status_command to "true" causes Chef
      to never call start on iptables-persistent,
      which is fine because any rule changes trigger
      a restart on iptables-persistent.

### Issues Resolved

Set status_command for iptables-persistent to "true".

    * iptables-persistent isn't a real service, so Chef
      can never find it in the process table and runs
      start on it every chef run, unnecessarily reloading
      the firewall rules when there is no change in the
      rule set.
    * Setting status_command to "true" causes Chef
      to never call start on iptables-persistent,
      which is fine because any rule changes trigger
      a restart on iptables-persistent.

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [ X ] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by williamsjj** [comment]
The build failed because a ruby gem failed to install not because test kitchen failed a test...is there a way to re-run a Travis build?

**Comment by martinb3** [comment]
If you rebase this on the latest master, I think it would resolve the gem installation issue and cause Travis to re-run tests when you push the rebased branch.

**Comment by martinb3** [comment]
Hello! I've merged this in as a new commit, since this PR already had three for just the one single line. Thank you for the contribution!

**Comment by williamsjj** [comment]
Yeah...if Travis hadn't barfed for unknown reasons on the the initial PR it would've merged then as a single commit.

**Pull request closed without merging**
