### PR TITLE
allow ipv6/esp/ah protocol passthrough for ufw

### PR DESCRIPTION
**Pull request by erkki**
### Description
allow ipv6/esp/ah protocols for ufw as per http://manpages.ubuntu.com/manpages/precise/man8/ufw.8.html
[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

Obvious fix. (ref https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD)

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @erkki

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by martinb3** [comment]
Hello! This has been open for a while, but the CLA isn't signed and the builds are currently failing. Please re-open when you have a chance to address these issues. Thank you!

**Comment by erkki** [comment]
Hello, I thought the "obvious fix" disclaimer would void the need for an CLA, correct/incorrect?

**Comment by martinb3** [comment]
Hi @erkki -- Ah, I do see you mentioned that in your commit message. TBH, I don't even read those until I see the tests are passing and the checklist is checked off. I can reopen this if you'd like to rebase and get the tests passing?

**Comment by erkki** [comment]
Noted, I don't think the travis failures have anything to do with the diff. I'll rebase against latest master and see if that helps.

**Comment by martinb3** [comment]
Looks like it's passed now. Thank you!

**Pull request merged**
