### PR TITLE
Adds ability to pass package options through to firewall package install

### PR DESCRIPTION
**Pull request by zeddicus76**
### Description

This change allows package_options to be passed through to the package install for firewall
### Issues Resolved

Our environment requires package_options to avoid hanging during the install. This modification allowed that to happen.
### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by martinb3** [comment]
Hi there -- would you mind adding [the DCO](https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD#developer-certification-of-origin-dco) to this commit?

**Comment by zeddicus76** [comment]
I am waiting to find out from my company how I get the OK to add the DCO.  It looks like I will be able to do it in the next week or so.

**Comment by martinb3** [comment]
You can also add "Obvious fix." to the commit message to invoke the [obvious fix](https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD#chef-obvious-fix-policy) clause, and skip the DCO. I think this commit would apply.

**Comment by zeddicus76** [comment]
Anything else I need to do for the Obvious Fix sign off?

**Comment by martinb3** [comment]
Hi there -- I cherry picked the two 'obvious fix' commits so I didn't have to merge this branch (it seems to have a lot of extra commits now via a merge commit). Have a look at master and be sure it looks good for your needs 👍 

Thanks for the contribution!

**Pull request closed without merging**
