### PR TITLE
Add disable_firewall recipe for use with clouds

### PR DESCRIPTION
**Pull request by Stromweld**
Signed-off-by: Corey Hemminger <corey.hemminger@nativex.com>

### Description

Adds recipe to disable OS firewall. This is best practice in many clouds like AWS that use their own firewall through Security Groups attached to an instance.

### Issues Resolved

Feature add.

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by martinb3** [comment]
Thanks @Stromweld!

**Comment by Stromweld** [comment]
Thanks for the merge. Would you be able to get it out to the community supermarket in the near future?

**Comment by martinb3** [comment]
@Stromweld Sure, releasing it in #165... just waiting for everything to pass 👍

**Comment by Stromweld** [comment]
sweet thanks

**Pull request merged**
